/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: schema.json
export type PathwayChoice = {
  _type: "pathwayChoice";
  label: LocalizedString;
  options?: Array<{
    _key: string;
  } & PathwayStep>;
};

export type PathwayStep = {
  _type: "pathwayStep";
  title: LocalizedString;
  description?: LocalizedString;
  kind: "priorEducation" | "certificate" | "associate" | "bachelor" | "master" | "doctoral" | "clinical" | "exam" | "credential" | "licensure" | "apprenticeship" | "other";
  requirement: "required" | "optional" | "recommended";
  organization?: string;
};

export type CareerHardFilter = {
  _type: "careerHardFilter";
  requiresLicensure?: boolean;
  requiresLifting?: boolean;
  requiresNightsWeekends?: boolean;
  requiresBloodNeedles?: boolean;
  requiresAcuteHighStress?: boolean;
  hasMinimumEducation?: boolean;
  educationLevel?: "FF" | "CSC" | "CERT" | "AAS" | "BACH" | "GRAD";
  hasMinimumSalary?: boolean;
  region?: string;
  note?: string;
};

export type Quiz = {
  _id: string;
  _type: "quiz";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: LocalizedString;
  questions?: Array<{
    order?: number;
    title?: LocalizedString;
    section?: "Interests & Values" | "Skills & Aptitudes" | "Work Environment" | "Schedule & Lifestyle" | "Education Path" | "Salary & Outlook" | "Location & Access" | "Career Features" | "Deal-breakers";
    prompt: LocalizedString;
    type?: "likert_5" | "rating_1_5" | "multi_select" | "single_select" | "boolean" | "region_select";
    maxSelect?: number;
    isDealbreaker?: boolean;
    options?: Array<{
      label: LocalizedString;
      weights?: {
        w_patient_facing?: number;
        w_tech_equipment?: number;
        w_lab_research?: number;
        w_counseling_education?: number;
        w_pediatrics?: number;
        w_geriatrics?: number;
        w_exposure_tolerance?: number;
        w_analytical?: number;
        w_admin?: number;
        w_procedural_dexterity?: number;
        w_collaboration?: number;
        w_pace_routine?: number;
        w_pace_fast?: number;
        w_schedule_flex?: number;
        w_stress_tolerance?: number;
        w_physical_light?: number;
        w_physical_on_feet?: number;
        w_physical_lifting?: number;
        w_env_hospital?: number;
        w_env_clinic?: number;
        w_env_community?: number;
        w_env_school?: number;
        w_env_lab?: number;
        w_env_office?: number;
        w_multi_env?: number;
        w_outlook_importance?: number;
        w_short_path?: number;
      };
      hardFilter?: HardFilter;
      _key: string;
    }>;
    _key: string;
  }>;
};

export type HardFilter = {
  _type: "hardFilter";
  requiresLicensure?: boolean;
  requiresLifting?: boolean;
  requiresNightsWeekends?: boolean;
  requiresBloodNeedles?: boolean;
  requiresAcuteHighStress?: boolean;
  hasMinimumEducation?: boolean;
  educationLevel?: "FF" | "CSC" | "CERT" | "AAS" | "BACH" | "GRAD";
  hasMinimumSalary?: boolean;
  region?: string;
  description?: string;
};

export type ProfessionalOrganization = {
  _id: string;
  _type: "professionalOrganization";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name: string;
  institution?: string;
  link?: string;
  description?: LocalizedText;
  membershipType?: Array<"student" | "professional" | "employer">;
  geographicFocus?: "virginia_statewide" | "regional" | "national" | "international" | "local";
  careerAreas?: Array<{
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: "careerCategory";
  }>;
};

export type Resource = {
  _id: string;
  _type: "resource";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  category: string;
  title: LocalizedString;
  summary?: LocalizedString;
  link: string;
  region?: string;
};

export type Scholarship = {
  _id: string;
  _type: "scholarship";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name: string;
  summary?: LocalizedString;
  description?: LocalizedText;
  institution?: string;
  eligibility?: LocalizedPortableText;
  region?: string;
  deadline?: string;
  link: string;
  currentStage?: Array<"high_school" | "college" | "graduate" | "working_professional" | "veteran_military" | "adult_returning">;
  fundingType?: "federal" | "state" | "institutional" | "private" | "foundation" | "other";
  locationScope?: "virginia_statewide" | "regional" | "national" | "local" | "international";
  careerAreas?: Array<{
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: "careerCategory";
  }>;
  badges?: Array<"undergraduate" | "graduate" | "undergraduate_graduate" | "multiple_cohorts" | "health_related">;
};

export type Program = {
  _id: string;
  _type: "program";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name: string;
  region?: string;
  credentialType?: string;
  duration?: Duration;
  cost?: MoneyRange;
  prerequisites?: LocalizedPortableText;
  accreditation?: LocalizedString;
  link?: string;
};

export type MoneyRange = {
  _type: "moneyRange";
  rangeMin?: number;
  rangeMax?: number;
  notes?: LocalizedString;
  source?: string;
  year?: number;
};

export type Duration = {
  _type: "duration";
  value?: number;
  unit?: "days" | "weeks" | "months" | "years";
};

export type CareerCategory = {
  _id: string;
  _type: "careerCategory";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  description?: LocalizedText;
};

export type Career = {
  _id: string;
  _type: "career";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: LocalizedString;
  slug?: Slug;
  summary?: LocalizedText;
  responsibilities?: LocalizedBulletList;
  workEnvironment?: LocalizedBulletList;
  specializations?: LocalizedBulletList;
  specializationsNote?: LocalizedPortableTextSmall;
  educationRequirements?: LocalizedPortableTextSmall;
  academicPathway?: AcademicPathway;
  prerequisites?: LocalizedPortableText;
  licensureAndCerts?: LocalizedBulletList;
  academicRequirementsHighlight?: LocalizedString;
  programLengthHighlight?: LocalizedString;
  salary?: Salary;
  outlook?: Outlook;
  quizVector?: {
    w_patient_facing?: number;
    w_tech_equipment?: number;
    w_lab_research?: number;
    w_counseling_education?: number;
    w_pediatrics?: number;
    w_geriatrics?: number;
    w_exposure_tolerance?: number;
    w_analytical?: number;
    w_admin?: number;
    w_procedural_dexterity?: number;
    w_collaboration?: number;
    w_pace_routine?: number;
    w_pace_fast?: number;
    w_schedule_flex?: number;
    w_stress_tolerance?: number;
    w_physical_light?: number;
    w_physical_on_feet?: number;
    w_physical_lifting?: number;
    w_env_hospital?: number;
    w_env_clinic?: number;
    w_env_community?: number;
    w_env_school?: number;
    w_env_lab?: number;
    w_env_office?: number;
    w_multi_env?: number;
    w_outlook_importance?: number;
    w_short_path?: number;
  };
  hardRequirements?: {
    requiresLicensure?: boolean;
    requiresLifting?: boolean;
    requiresNightsWeekends?: boolean;
    requiresBloodNeedles?: boolean;
    requiresAcuteStress?: boolean;
    hasMinimumEducation?: boolean;
    educationLevel?: "FF" | "CSC" | "CERT" | "AAS" | "BACH" | "GRAD";
    hasMinimumSalary?: boolean;
    region?: string;
  };
  categories?: Array<{
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: "careerCategory";
  }>;
  similarCareers?: Array<{
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: "career";
  }>;
  programs?: Array<{
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: "program";
  }>;
  educationInstitutions?: Array<{
    institution: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "educationalInstitution";
    };
    programUrl?: string;
    label?: string;
    _type: "educationInstitutionItem";
    _key: string;
  }>;
  scholarships?: Array<{
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: "scholarship";
  }>;
  professionalOrgs?: Array<{
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: "professionalOrganization";
  }>;
  resources?: Array<{
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: "resource";
  }>;
  images?: Array<{
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
    _key: string;
  }>;
  videoUrl?: string;
  videoClosedCaptions?: LocalizedBulletList;
  videoCaptionCycleSeconds?: number;
  lastReviewedAt?: string;
  lastUpdatedAt?: string;
};

export type EducationalInstitution = {
  _id: string;
  _type: "educationalInstitution";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name: string;
  slug?: Slug;
  location: Geopoint;
  address?: string;
  website?: string;
  region?: "Northern VA" | "Blue Ridge" | "Rappahannock" | "Central" | "Southside" | "Eastern VA" | "South Central" | "Southwest";
};

export type Outlook = {
  _type: "outlook";
  label?: string;
  value?: number;
  notes?: LocalizedString;
  source?: string;
  year?: number;
};

export type Salary = {
  _type: "salary";
  median?: number;
  rangeMin?: number;
  rangeMax?: number;
  notes?: LocalizedString;
  source?: string;
  year?: number;
};

export type LocalizedPortableText = {
  _type: "localizedPortableText";
  en: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h2" | "h3";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  es?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h2" | "h3";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
};

export type AcademicPathway = {
  _type: "academicPathway";
  status: "draft" | "inReview" | "verified";
  verifiedAt?: string;
  editorNotes?: string;
  items?: Array<{
    _key: string;
  } & PathwayStep | {
    _key: string;
  } & PathwayChoice>;
};

export type LocalizedPortableTextSmall = {
  _type: "localizedPortableTextSmall";
  en: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "small";
    listItem?: never;
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  es?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "small";
    listItem?: never;
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
};

export type LocalizedBulletList = {
  _type: "localizedBulletList";
  en: Array<string>;
  es?: Array<string>;
};

export type HomePage = {
  _id: string;
  _type: "homePage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  heroVideoUrl?: string;
  featuredCareers?: Array<{
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: "career";
  }>;
};

export type SiteSettings = {
  _id: string;
  _type: "siteSettings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  navLinks?: Array<{
    label: LocalizedString;
    href: string;
    _key: string;
  }>;
  footerLinks?: Array<{
    label: LocalizedString;
    href: string;
    _key: string;
  }>;
  announcements?: LocalizedText;
  featureFlags?: {
    aiChatEnabled?: boolean;
    scholarshipsEnabled?: boolean;
  };
  seoDefaults?: {
    title?: LocalizedString;
    description?: LocalizedText;
  };
};

export type LocalizedText = {
  _type: "localizedText";
  en: string;
  es?: string;
};

export type LocalizedString = {
  _type: "localizedString";
  en: string;
  es?: string;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type Slug = {
  _type: "slug";
  current: string;
  source?: string;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type AllSanitySchemaTypes = PathwayChoice | PathwayStep | CareerHardFilter | Quiz | HardFilter | ProfessionalOrganization | Resource | Scholarship | Program | MoneyRange | Duration | CareerCategory | Career | EducationalInstitution | Outlook | Salary | LocalizedPortableText | AcademicPathway | LocalizedPortableTextSmall | LocalizedBulletList | HomePage | SiteSettings | LocalizedText | LocalizedString | SanityImagePaletteSwatch | SanityImagePalette | SanityImageDimensions | SanityImageHotspot | SanityImageCrop | SanityFileAsset | SanityImageAsset | SanityImageMetadata | Geopoint | Slug | SanityAssetSourceData;
export declare const internalGroqTypeReferenceTo: unique symbol;
